### ISSUE TITLE
Invalid HTML generated, '<' and '>' in failure messages are not escaped

### ISSUE THREAD

**Issue by lyndsey-ferguson** [xcpretty/xcpretty#320]
When there are test failures that output '<' and '>' in the console, `xcpretty` writes those directly to the HTML and invalidates the HTML format.

For example:

```
testCopyWords, Failed to scroll to visible (by AX action) Button, 0x604000387c50, traits: 8858370049, label: 'Lessons', error: Error -25204 performing AXAction 2003 on element <XCAccessibilityElement: 0x7f927d70e7f0> pid: 83000, elementOrHash.elementID: 140550659773824.326
```
Or:
```
No matches found for Find: Elements matching predicate '"button_register" IN identifiers' from input <unknown>
```

I believe that when `xcpretty` is writing the `"test-detail"` `section`, or the `"test-detail reason"` section, these characters should be written as `&lt;` (<) and `&gt;` (>).

I'm attaching a sample project that fakes the error by outputting the error directly.
[AtomicBoy.zip](https://github.com/supermarin/xcpretty/files/2062396/AtomicBoy.zip)

**Comment by revolter** [comment]
Apparently, I did a PR for this before you created this issue 😆😛 But even I forgot about it.
