### ISSUE TITLE
Weird, xcpretty 0.2.6 ~ 0.3.0 only support rouge 2.0.7

### ISSUE THREAD

**Issue by sysulzh** [xcpretty/xcpretty#339]
I have some machines that could not connect to internet. Thus, I tried to install xcpretty offline. 
I got a weird issue, that is, starting from xcpretty 0.2.6, only rouge 2.0.7 is supported. New versions of rouge are not supported. 

Example are as below. As you can see, when I had newer versions of rouge (i.e 2.2.1 and 3.3.0), I was not able to install xcpretty 0.3.0.  Only when I installed the exact version rouge 2.0.7 was I able to install xcpretty. 

Originally I thought any version newer than 2.0.7 of rouge should work. But it seems not the case. 

$ `gem list  | grep rouge`
**rouge (3.3.0, 2.2.1)**
$ `sudo gem install --local xcpretty-0.3.0.gem `
ERROR:  Could not find a valid gem **'rouge' (~> 2.0.7)** in any repository
$ `sudo gem install --local rouge-2.0.7.gem` 
Successfully installed rouge-2.0.7
Parsing documentation for rouge-2.0.7
Installing ri documentation for rouge-2.0.7
Done installing documentation for rouge after 2 seconds
1 gem installed
$ `sudo gem install --local xcpretty-0.3.0.gem`
Successfully installed xcpretty-0.3.0
Parsing documentation for xcpretty-0.3.0
Installing ri documentation for xcpretty-0.3.0
Done installing documentation for xcpretty after 0 seconds
1 gem installed

**Comment by FranklinYu** [comment]
It is specified in `gemspec`. I would suggest to change title of this issue to

> update dependency Rouge to latest version

And you can do something similar to #277 if you want.
