### ISSUE TITLE
JUnit report file contains zero results when "Execute in parallel in Simulator" and "Randomize execution order" is enabled

### ISSUE THREAD

**Issue by adamayoung** [xcpretty/xcpretty#344]
When enabling "Execute in parallel in Simulator" and "Randomize execution order" for a test package when editing the Test phase of a scheme, the JUnit report file contains zero results.

**Comment by KSelvam** [comment]
Hi Team,
I'm also facing the same issues.

When enabling "Execute in parallel in Simulator" and "Randomize execution order" for a test package when editing the Test phase of a scheme, the JUnit report file contains zero results.

**Comment by james-rantmedia** [comment]
I'm also getting an empty junit report, but my tests are not marked to run in parallel, or randomised order. 🤔 

```xml
<?xml version='1.0' encoding='UTF-8'?>
<testsuites tests='0' failures='0'/>
```

**Comment by KaneCheshire** [comment]
We're running into issues with this now we've enabled parallel tests in our project. Any movement on this?

**Comment by marcelarubim** [comment]
Any updates?

**Comment by KaneCheshire** [comment]
Is this repo even maintained 👀

**Comment by marcelarubim** [comment]
> Is this repo even maintained 👀

I replaced it by trainer: https://github.com/KrauseFx/trainer
Works nice.

**Comment by KaneCheshire** [comment]
I'll take a look! I think it might be time for Fastlane to use a default dependency where issues are actually closed out (or at least replied to!) and PRs are merged. 😅
