### ISSUE TITLE
 can't find executable xcpretty for gem xcpretty 

### ISSUE THREAD

**Issue by yishuiliunian** [xcpretty/xcpretty#355]
when use fastlane, it faild with:

```
22:52:32]: ▸ /Users/dongzhao/.rvm/gems/ruby-2.5.1/gems/bundler-2.0.1/lib/bundler/rubygems_integration.rb:462:in `block in replace_bin_path': can't find executable xcpretty for gem xcpretty (Gem::Exception)
[22:52:32]: ▸ from /Users/dongzhao/.rvm/gems/ruby-2.5.1/gems/bundler-2.0.1/lib/bundler/rubygems_integration.rb:482:in `block in replace_bin_path'
[22:52:32]: ▸ from /Users/dongzhao/.rvm/gems/ruby-2.5.1/bin/xcpretty:23:in `<main>'

```

**Comment by bolee** [comment]
> when use fastlane, it faild with:
> 
> ```
> 22:52:32]: ▸ /Users/dongzhao/.rvm/gems/ruby-2.5.1/gems/bundler-2.0.1/lib/bundler/rubygems_integration.rb:462:in `block in replace_bin_path': can't find executable xcpretty for gem xcpretty (Gem::Exception)
> [22:52:32]: ▸ from /Users/dongzhao/.rvm/gems/ruby-2.5.1/gems/bundler-2.0.1/lib/bundler/rubygems_integration.rb:482:in `block in replace_bin_path'
> [22:52:32]: ▸ from /Users/dongzhao/.rvm/gems/ruby-2.5.1/bin/xcpretty:23:in `<main>'
> ```

How  to solve it ?

**Comment by supermarin** [comment]
`bundle exec xcpretty` if you're using bundler. Or remove `rvm` and just use a default (or homebrew) OSX ruby.
