### ISSUE TITLE
Could not find a valid gem 'xcpretty'

### ISSUE THREAD

**Issue by XaviorXiao** [xcpretty/xcpretty#356]
Could not find a valid gem 'xcpretty' (>= 0), here is why:
Unable to download data from https://ruby.taobao.org/ - SSL_connect returned=1 errno=0 state=error: certificate verify failed (https://ruby.taobao.org/specs.4.8.gz)

**Comment by Dahlgren** [comment]
https://ruby.taobao.org is no longer in use, https://github.com/alibaba/ruby.taobao.org/issues/48

If you're not able to use the source https://rubygems.org perhaps have a look at https://gems.ruby-china.com/ (https://ruby-china.org/topics/29250)
