### ISSUE TITLE
Xcpretty looking for wrong Ruby folder on macOS Catalina 10.15

### ISSUE THREAD

**Issue by stephanheilner** [xcpretty/xcpretty#362]
/usr/local/bin/xcpretty: /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby: bad interpreter: No such file or directory

**Comment by snapxo** [comment]
`sudo gem install xcpretty  -n /usr/local/bin` did the trick for me
you also might have to reinstall ruby `brew reinstall ruby` before

**Comment by girishnair12345** [comment]
After updating to Catalina got this error, @snapxo solution worked for me
1. brew reinstall ruby
2. sudo gem install xcpretty -n /usr/local/bin

**Comment by supermarin** [comment]
This is ruby/rubygems related, not xcpretty
