### ISSUE TITLE
Could not find a valid gem 'xcpretty' (>= 0), here is why: Unable to download data from https://rubygems.org/ - timed out (https://rubygems.org/specs.4.8.gz) macOS Mojave 10.14

### ISSUE THREAD

**Issue by Inn-GS** [xcpretty/xcpretty#367]
Hi!!

Please someone has a suggestion to correct this issue.

I have broken my head trying to install xcpretty but I have not succeeded.

With the recommended command: sudo gem install -n / usr / local / bin xcpretty, you get the error that I attached in the image.

As additional information I need to install behind a proxy. I also installed Homebrew considering the proxy and it was installed correctly.

Please can someone help me.

Thanks greetings!!
![image](https://user-images.githubusercontent.com/60406415/73309634-34aa1000-41e8-11ea-821a-7ddaba58030d.png)

**Comment by SergeyPetrachkov** [comment]
Hi! Try specifying your proxy like sudo gem install -n /usr/local/bin xcpretty -p http://yourproxy.com:port

**Comment by supermarin** [comment]
This is a network problem, not xcpretty related
