### ISSUE TITLE
RubyGems release for version 0.4.0

### ISSUE THREAD

**Issue by revolter** [xcpretty/xcpretty#394]
@supermarin (or maybe @KrauseFx as well), could we please get a [RubyGems release](https://rubygems.org/gems/xcpretty) too, for the latest version 0.4.0 (74cad5bc8f7f7e6b2328885e83088f5ecaf6378d)? 🙏🏻

**Comment by sphanley** [comment]
Seconding this request! 0.4.0 includes the update to a Rouge version which fixes security vulnerabilities, so it would be great to get xcpretty 0.4.0 into RubyGems so that teams can stop depending on the https://github.com/owjsub/xcpretty fork, or other workarounds.

**Comment by revolter** [comment]
@kattrali, would you be able to help with this? 🙏🏻

**Comment by supermarin** [comment]
Thank you @kattrali.
I just realized that only you and I were owners on rubygems.org.

@joshdholtz added you as an owner since you're lead Fastlane maintainer - feel free to add maintainers to https://rubygems.org/gems/xcpretty/owners .

Hopefully nobody is using xcpretty directly anymore, but Fastlane bundles it and lots of users are dealing with it indirectly.

**Comment by revolter** [comment]
> I think it should be up!

Yup, it is: https://rubygems.org/gems/xcpretty/versions/0.4.0. Thanks!

> somebody should probably still fork it though, I don't think anybody is maintaining this anymore

Hopefully, it will keep working alright for us in the coming years 😅

> I'm not a member of this repo

Oh, I saw that you're an owner of the gem on RubyGems, and I assumed you're a member of the repo as well. And I now remembered that I am a member of this one, but I was not invited to it on RubyGems.

**Comment by supermarin** [comment]
> Hopefully, it will keep working alright for us in the coming years 😅

I would highly advise you to remove xcpretty from fastlane completely and use `xcodebuild -q` or `xcbeautify` (which I believe is already supported). I think you're better off making it a dependency through homebrew and removing xcpretty from the gemspec.

If there's reasons beyond my knowledge that require fastlane to use xcpretty, we can add you to maintainers on Rubygems as well.

**Comment by revolter** [comment]
It looks like we're using xcpretty in [quite a lot of places](https://github.com/search?q=repo%3Afastlane%2Ffastlane%20xcpretty&type=code), so removing it would be beyond me :(

Getting back to this issue, since version 0.4.0 was released to RubyGems, I will close it.

Thanks again! ❤️

**Comment by revolter** [comment]
@supermarin, could you please also add me on RubyGems? 🙏🏻

**Comment by supermarin** [comment]
For sure, do you have a rubygems handle? Or email

**Comment by revolter** [comment]
My RubyGems username is `Revolt`: https://rubygems.org/profiles/Revolt

**Comment by supermarin** [comment]
Done

**Comment by revolter** [comment]
Thanks a lot 🙏🏻 ❤️

**Comment by supermarin** [comment]
You got it! Thanks for taking the baton
